spring:
  datasource:
    password: 1234
    username: postgres
    url: jdbc:postgresql://localhost:5432/shoes_shop
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 40MB
      max-request-size: 40MB
file:
  upload:
    path: C:\Users\sayda\OneDrive\Рабочий стол\shoes data server
    base-url: http://localhost:8080

server:
  address: 0.0.0.0
